# ################################
# Model: Whisper (Encoder-Decoder) + NLL
# Augmentation: TimeDomainSpecAugment
# Authors: Adel Moumen 2022, Titouan Parcollet 2022
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1986
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref BMOHA/results
wer_file: !ref <output_folder>/werDecider.txt
save_folder: !ref <output_folder>/save

# URL for the biggest Fairseq english whisper model.
whisperTiny_hub: openai/whisper-tiny
whisperTiny_folder: !ref <save_folder>/whisperTiny_checkpoint
whisperMedium_hub: openai/whisper-small
whisperMedium_folder: !ref <save_folder>/whisperMedium_checkpoint
language: english

# Normalize the english inputs with
# the same normalization done in the paper
normalized_transcripts: True
test_only: True # Set it to True if you only want to  do the evaluation

# Data files
data_folder: /scratch1/data/raw_data/LibriSpeech  # e,g./path/to/CommonVoice
skip_prep: False
train_csv: !ref <save_folder>/train-WER.csv
valid_csv: !ref <save_folder>/dev-WER.csv
test_csv: !ref <save_folder>/test-WER.csv

ckpt_interval_minutes: 30 # save checkpoint every N min

# Training parameters
number_of_epochs: 1
lr_whisper: 0.00003
sorting: ascending
auto_mix_prec: False
sample_rate: 16000

# With data_parallel batch_size is split into N jobs
# With DDP batch_size is multiplied by N jobs
batch_size: 1
test_batch_size: 1 #8

# These values are only used for the searchers.
# They needs to be hardcoded and should not be changed with Whisper.
# They are used as part of the searching process.
# The bos token of the searcher will be timestamp_index
# and will be concatenated with the bos, language and task tokens.
timestamp_index: 50363
eos_index: 50257
bos_index: 50258

# Decoding parameters
min_decode_ratio: 0.0
max_decode_ratio: 1.0
test_beam_size: 8

# Model parameters
freeze_whisper: False


train_loader_kwargs:
    batch_size: !ref <batch_size>

valid_loader_kwargs:
    batch_size: !ref <batch_size>

test_loader_kwargs:
    batch_size: !ref <test_batch_size>


#
# Functions and classes
#
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

whisperTiny: !new:speechbrain.lobes.models.huggingface_whisper.HuggingFaceWhisper
    source: !ref <whisperTiny_hub>
    freeze: !ref <freeze_whisper>
    save_path: !ref <save_folder>/whisper_checkpoint
    encoder_only: False

whisperMedium: !new:speechbrain.lobes.models.huggingface_whisper.HuggingFaceWhisper
    source: !ref <whisperMedium_hub>
    freeze: !ref <freeze_whisper>
    save_path: !ref <save_folder>/whisper_checkpoint
    encoder_only: False

decider: !new:convolution_whisper_space.ResNet1DPonderate
    n_blocks: 3
    channels: [256,256,256]
    input_channels: 768
    nbCoef: 13

#Put down here the path to the trained model you want to infere with
decider_path: BMOHA/train_cnn/best/resnet.ckpt 


log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

nll_loss: !name:speechbrain.nnet.losses.nll_loss

modules:
    whisperTiny: !ref <whisperTiny>
    whisperMedium: !ref <whisperMedium>
    decider: !ref <decider>

whisper_opt_class: !name:torch.optim.AdamW
    lr: !ref <lr_whisper>
    weight_decay: 0.01

test_beam_searcher_tiny: !new:speechbrain.decoders.seq2seq.S2SWhisperBeamSearch
    module: [!ref <whisperTiny>]
    bos_index: !ref <timestamp_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: !ref <test_beam_size>

test_beam_searcher_medium: !new:speechbrain.decoders.seq2seq.S2SWhisperBeamSearch
    module: [!ref <whisperMedium>]
    bos_index: !ref <timestamp_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: !ref <test_beam_size>

lr_annealing_whisper: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr_whisper>
    improvement_threshold: 0.0025
    annealing_factor: 0.9
    patient: 0

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        whisper: !ref <whisperTiny>
        scheduler_whisper: !ref <lr_annealing_whisper>
        counter: !ref <epoch_counter>

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True
